# Generated by Django 5.1.4 on 2024-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermood',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
