# Generated by Django 4.2.17 on 2024-12-19 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_usermood_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermood',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
