# Generated by Django 5.1.4 on 2024-12-19 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_alter_usermood_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('mood_type', models.CharField(max_length=50)),
                ('weather_condition', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_moods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
