# Generated by Django 4.2.17 on 2024-12-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0004_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermood',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
