# Generated by Django 4.2.17 on 2024-12-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0007_remove_customuser_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermood',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
