# Generated by Django 4.2.17 on 2024-12-19 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0004_dynamicmood'),
        ('moods', '0008_customuser_latitude_customuser_longitude_and_more'),
    ]

    operations = [
    ]
