# Generated by Django 4.2.17 on 2024-12-19 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0009_merge_20241220_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicMood',
        ),
    ]
